stages:
  - build
  - deploy

build:
  stage: build
  image: docker:19.03.8
  tags:
    - gitlab-org-docker
  services:
    - docker:19.03.8-dind   
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:$PROJECT_NAME-latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:$PROJECT_NAME-latest --tag $CI_REGISTRY_IMAGE:$PROJECT_NAME-$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:$PROJECT_NAME-latest .
    - docker push $CI_REGISTRY_IMAGE:$PROJECT_NAME-$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$PROJECT_NAME-latest
  rules: 
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "stag"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "Integration_Optimization"'
      when: always


.deploy_template: &deploy_template
  stage: deploy
  image: docker:19.03.8
  tags:
    - gitlab-org-docker
  services:
    - docker:19.03.8-dind   
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

Dev:
  <<: *deploy_template
  before_script:
    - apk update && apk add bash
    - apk add --no-cache su-exec
    - apk add --no-cache sudo
    - echo $CI_BUILD_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker run -v ${PWD}/target:/home/node/app/target --name $PROJECT_NAME $CI_REGISTRY_IMAGE:$PROJECT_NAME-latest $ENV $PLUGIN $TAG
    - docker logs -f $PROJECT_NAME
  artifacts:
    when: always
    reports:
      junit:
        - ${PWD}/target/cucumber-report/Cucumber.xml
  rules:
    - if: '$CI_COMMIT_BRANCH == "Integration_Optimization"'
      when: always

staging:
  <<: *deploy_template
  before_script:
    - apk update && apk add bash
    - apk add --no-cache su-exec
    - apk add --no-cache sudo
    - echo $CI_BUILD_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY 
  script:
    - docker run -v ${PWD}/target:/home/node/app/target --name $PROJECT_NAME $CI_REGISTRY_IMAGE:$PROJECT_NAME-latest $ENV $PLUGIN $TAG
    - docker logs -f $PROJECT_NAME
  artifacts:
    when: always
    reports:
      junit:
        - ${PWD}/target/cucumber-report/Cucumber.xml
  rules:
    - if: '$CI_COMMIT_BRANCH == "stag"'
      when: always

US1:
  <<: *deploy_template
  before_script:
    - apk update && apk add bash
    - apk add --no-cache su-exec
    - apk add --no-cache sudo
    - echo $CI_BUILD_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY 
  script:
    - chmod +x etc-hosts.sh
    - ./etc-hosts.sh addhost cloud-api.loginradius.com 3.227.111.1
    - cat /etc/hosts
    - docker run -v ${PWD}/target:/home/node/app/target --name $PROJECT_NAME $CI_REGISTRY_IMAGE:$PROJECT_NAME-latest $ENV $PLUGIN $TAG
    - docker logs -f $PROJECT_NAME
  artifacts:
    when: always
    reports:
      junit:
        - ${PWD}/target/cucumber-report/Cucumber.xml
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual

CA2:
  <<: *deploy_template
  before_script:
    - apk update && apk add bash
    - apk add --no-cache su-exec
    - apk add --no-cache sudo
    - echo $CI_BUILD_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY 
  script:
    - chmod +x etc-hosts.sh
    - ./etc-hosts.sh addhost cloud-api.loginradius.com 52.228.71.198
    - cat /etc/hosts
    - docker run -v ${PWD}/target:/home/node/app/target --name $PROJECT_NAME $CI_REGISTRY_IMAGE:$PROJECT_NAME-latest $ENV $PLUGIN $TAG
    - docker logs -f $PROJECT_NAME
  artifacts:
    when: always
    reports:
      junit:
        - ${PWD}/target/cucumber-report/Cucumber.xml
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual

AP1:
  <<: *deploy_template
  before_script:
    - apk update && apk add bash
    - apk add --no-cache su-exec
    - apk add --no-cache sudo
    - echo $CI_BUILD_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY 
  script:
    - chmod +x etc-hosts.sh
    - ./etc-hosts.sh addhost cloud-api.loginradius.com 168.63.206.152
    - cat /etc/hosts
    - docker run -v ${PWD}/target:/home/node/app/target --name $PROJECT_NAME $CI_REGISTRY_IMAGE:$PROJECT_NAME-latest $ENV $PLUGIN $TAG
    - docker logs -f $PROJECT_NAME
  artifacts:
    when: always
    reports:
      junit:
        - ${PWD}/target/cucumber-report/Cucumber.xml
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual

EU1:
  <<: *deploy_template
  before_script:
    - apk update && apk add bash
    - apk add --no-cache su-exec
    - apk add --no-cache sudo
    - echo $CI_BUILD_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY 
  script:
    - chmod +x etc-hosts.sh
    - ./etc-hosts.sh addhost cloud-api.loginradius.com 63.33.156.194
    - cat /etc/hosts
    - docker run -v ${PWD}/target:/home/node/app/target --name $PROJECT_NAME $CI_REGISTRY_IMAGE:$PROJECT_NAME-latest $ENV $PLUGIN $TAG
    - docker logs -f $PROJECT_NAME
  artifacts:
    when: always
    reports:
      junit:
        - ${PWD}/target/cucumber-report/Cucumber.xml
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual